### ISSUE TITLE
ModuleNotFoundError: No module named 'rf_baseline'

### ISSUE THREAD

**Issue by izaskr** [aeye-lab/etra-reading-comprehension#2]
Hi,

Thank you for making this code public. I'm facing an issue when running the generate_text_sequence_splits.py as instructed.
```

Traceback (most recent call last):
  File "/local/home/work/izaskr/etra-reading-comprehension/utils/generate_text_sequence_splits.py", line 10, in <module>
    import rf_baseline.rf_feature_extraction as rfe
ModuleNotFoundError: No module named 'rf_baseline'
```

I didn't find any information on `rf_baseline` in the code base. 

Before running the command above, I also had issues with installing the requirements ("The user requested joblib==0.17.0,  scikit-learn 1.1.1 depends on joblib>=1.0.0"), so I installed joblib 1.1.0. The pandas library was also missing from the requirements.

Thanks for the help!

**Comment by SiQube** [comment]
thank you for the first issue on this repository! I've fixed the issue in the two pull requests -- hope everything works now. Otherwise, you can open another issue and I'll get back to you asap!
